# Generated by Django 5.0.1 on 2024-03-04 10:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank='True', max_length=255, null=True)),
                ('video', models.FileField(blank=True, upload_to='videoes')),
                ('image', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpeg', 'jpg'], message="Enter an image in the format below('ico','png','jpeg','jpg')")])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank='True', max_length=255, null=True)),
                ('video', models.FileField(blank=True, upload_to='videoes')),
                ('image', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpeg', 'jpg'], message="Enter an image in the format below('ico','png','jpeg','jpg')")])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('worker', 'Ishchi'), ('student', 'Shogird')], default='worker', help_text='Choose positions', max_length=55, verbose_name='Enter the position')),
                ('full_name', models.CharField(max_length=155, verbose_name='Enter the name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Enter the phone number')),
                ('image', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpeg', 'jpg'], message="Enter an image in the format below('ico','png','jpeg','jpg')")])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('telegram_id', models.CharField(max_length=10, verbose_name='Telegram_ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Enter the task !')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('fbb26646-2859-4e11-b88f-e189a394ad64'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('active', 'Aktiv'), ('progress', 'Jarayonda'), ('done', 'Bajarildi')], default='active', help_text='Choose status', max_length=15, verbose_name='Enter the status')),
                ('name', models.TextField(verbose_name='Enter the task !')),
                ('image', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpeg', 'jpg'], message="Enter an image in the format below('ico','png','jpeg','jpg')")])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(blank=True, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='app.telegramuser'),
        ),
    ]
