# Generated by Django 5.0.1 on 2024-03-04 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('67f8e6ea-cb7b-445f-9b74-3392a1fc26c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
