# Generated by Django 5.0.1 on 2024-03-04 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9db0658c-51ff-4f46-9bb1-12614adc6a93'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
