# Generated by Django 5.0.1 on 2024-03-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.telegramuser'),
        ),
    ]
