# Generated by Django 5.0.1 on 2024-03-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_complaint_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='tasks_accepted', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='text',
            field=models.CharField(blank='True', max_length=955, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to='app.employee'),
        ),
    ]
